// 12 System Themes

import type { ThemeConfig } from "./types";

export const SYSTEM_THEMES: ThemeConfig[] = [
  // 1. Midnight Hacker Den
  {
    id: "midnight-hacker",
    name: "Midnight Hacker Den",
    description: "Dark purple with neon accents and lo-fi beats",
    isSystem: true,
    isPremium: false,
    colors: {
      primary: "#a78bfa",
      secondary: "#c084fc",
      background: "#0f0a1e",
      foreground: "#e9d5ff",
      accent: "#8b5cf6",
      muted: "#1e1b2e",
      border: "#2d2640",
      card: "#1a1528",
      cardForeground: "#e9d5ff",
      popover: "#1a1528",
      popoverForeground: "#e9d5ff",
      destructive: "#ef4444",
      destructiveForeground: "#fef2f2",
      success: "#10b981",
      warning: "#f59e0b",
      info: "#3b82f6",
    },
    gradients: {
      hero: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
      card: "linear-gradient(135deg, #1a1528 0%, #2d2640 100%)",
      button: "linear-gradient(135deg, #8b5cf6 0%, #a78bfa 100%)",
      background: "linear-gradient(180deg, #0f0a1e 0%, #1a1528 100%)",
    },
    particles: {
      enabled: true,
      density: 50,
      color: "#a78bfa",
      speed: 1,
      size: 3,
      opacity: 0.5,
      shape: "circle",
    },
    soundscape: {
      enabled: true,
      url: "/sounds/lofi-beats.mp3",
      volume: 0.3,
      loop: true,
      fadeIn: 2000,
      fadeOut: 2000,
    },
    animations: {
      enabled: true,
      intensity: "medium",
      duration: 300,
      easing: "ease-in-out",
    },
  },

  // 2. Sunset Beach Studio
  {
    id: "sunset-beach",
    name: "Sunset Beach Studio",
    description: "Warm colors with ocean wave sounds",
    isSystem: true,
    isPremium: false,
    colors: {
      primary: "#f97316",
      secondary: "#fb923c",
      background: "#fff7ed",
      foreground: "#431407",
      accent: "#ea580c",
      muted: "#ffedd5",
      border: "#fed7aa",
      card: "#fffbeb",
      cardForeground: "#431407",
      popover: "#fffbeb",
      popoverForeground: "#431407",
      destructive: "#dc2626",
      destructiveForeground: "#fef2f2",
      success: "#059669",
      warning: "#d97706",
      info: "#0284c7",
    },
    gradients: {
      hero: "linear-gradient(135deg, #f97316 0%, #fb923c 100%)",
      card: "linear-gradient(135deg, #fffbeb 0%, #ffedd5 100%)",
      button: "linear-gradient(135deg, #ea580c 0%, #f97316 100%)",
      background: "linear-gradient(180deg, #fff7ed 0%, #ffedd5 100%)",
    },
    particles: {
      enabled: true,
      density: 30,
      color: "#fb923c",
      speed: 0.5,
      size: 4,
      opacity: 0.3,
      shape: "circle",
    },
    soundscape: {
      enabled: true,
      url: "/sounds/ocean-waves.mp3",
      volume: 0.4,
      loop: true,
      fadeIn: 3000,
      fadeOut: 3000,
    },
    animations: {
      enabled: true,
      intensity: "low",
      duration: 400,
      easing: "ease-out",
    },
  },

  // 3. Cyberpunk Rush
  {
    id: "cyberpunk-rush",
    name: "Cyberpunk Rush",
    description: "High-energy synthwave with neon aesthetics",
    isSystem: true,
    isPremium: true,
    colors: {
      primary: "#ff00ff",
      secondary: "#00ffff",
      background: "#0a0a0f",
      foreground: "#ffffff",
      accent: "#ff0080",
      muted: "#1a1a2e",
      border: "#ff00ff",
      card: "#16161f",
      cardForeground: "#ffffff",
      popover: "#16161f",
      popoverForeground: "#ffffff",
      destructive: "#ff0040",
      destructiveForeground: "#ffffff",
      success: "#00ff80",
      warning: "#ffff00",
      info: "#00ffff",
    },
    gradients: {
      hero: "linear-gradient(135deg, #ff00ff 0%, #00ffff 100%)",
      card: "linear-gradient(135deg, #16161f 0%, #1a1a2e 100%)",
      button: "linear-gradient(135deg, #ff0080 0%, #ff00ff 100%)",
      background: "linear-gradient(180deg, #0a0a0f 0%, #16161f 100%)",
    },
    particles: {
      enabled: true,
      density: 80,
      color: "#ff00ff",
      speed: 2,
      size: 2,
      opacity: 0.7,
      shape: "square",
    },
    soundscape: {
      enabled: true,
      url: "/sounds/synthwave.mp3",
      volume: 0.5,
      loop: true,
      fadeIn: 1000,
      fadeOut: 1000,
    },
    animations: {
      enabled: true,
      intensity: "high",
      duration: 200,
      easing: "ease-in-out",
    },
  },

  // 4. Forest Sanctuary
  {
    id: "forest-sanctuary",
    name: "Forest Sanctuary",
    description: "Nature sounds with zen mode",
    isSystem: true,
    isPremium: false,
    colors: {
      primary: "#22c55e",
      secondary: "#4ade80",
      background: "#f0fdf4",
      foreground: "#14532d",
      accent: "#16a34a",
      muted: "#dcfce7",
      border: "#bbf7d0",
      card: "#f7fee7",
      cardForeground: "#14532d",
      popover: "#f7fee7",
      popoverForeground: "#14532d",
      destructive: "#dc2626",
      destructiveForeground: "#fef2f2",
      success: "#16a34a",
      warning: "#ca8a04",
      info: "#0284c7",
    },
    gradients: {
      hero: "linear-gradient(135deg, #22c55e 0%, #4ade80 100%)",
      card: "linear-gradient(135deg, #f7fee7 0%, #dcfce7 100%)",
      button: "linear-gradient(135deg, #16a34a 0%, #22c55e 100%)",
      background: "linear-gradient(180deg, #f0fdf4 0%, #dcfce7 100%)",
    },
    particles: {
      enabled: true,
      density: 20,
      color: "#4ade80",
      speed: 0.3,
      size: 5,
      opacity: 0.2,
      shape: "circle",
    },
    soundscape: {
      enabled: true,
      url: "/sounds/forest-birds.mp3",
      volume: 0.3,
      loop: true,
      fadeIn: 4000,
      fadeOut: 4000,
    },
    animations: {
      enabled: true,
      intensity: "low",
      duration: 500,
      easing: "ease",
    },
  },

  // 5. Coffee Shop Co-work
  {
    id: "coffee-shop",
    name: "Coffee Shop Co-work",
    description: "Café ambience for focused work",
    isSystem: true,
    isPremium: false,
    colors: {
      primary: "#92400e",
      secondary: "#b45309",
      background: "#fef3c7",
      foreground: "#451a03",
      accent: "#d97706",
      muted: "#fde68a",
      border: "#fcd34d",
      card: "#fef9c3",
      cardForeground: "#451a03",
      popover: "#fef9c3",
      popoverForeground: "#451a03",
      destructive: "#dc2626",
      destructiveForeground: "#fef2f2",
      success: "#16a34a",
      warning: "#d97706",
      info: "#0284c7",
    },
    gradients: {
      hero: "linear-gradient(135deg, #92400e 0%, #d97706 100%)",
      card: "linear-gradient(135deg, #fef9c3 0%, #fde68a 100%)",
      button: "linear-gradient(135deg, #b45309 0%, #d97706 100%)",
      background: "linear-gradient(180deg, #fef3c7 0%, #fde68a 100%)",
    },
    particles: {
      enabled: false,
      density: 0,
      color: "#d97706",
      speed: 0,
      size: 0,
      opacity: 0,
      shape: "circle",
    },
    soundscape: {
      enabled: true,
      url: "/sounds/cafe-ambience.mp3",
      volume: 0.4,
      loop: true,
      fadeIn: 2000,
      fadeOut: 2000,
    },
    animations: {
      enabled: true,
      intensity: "low",
      duration: 400,
      easing: "ease-out",
    },
  },

  // 6. Space Station Lab
  {
    id: "space-station",
    name: "Space Station Lab",
    description: "Cosmic atmosphere with ambient sounds",
    isSystem: true,
    isPremium: true,
    colors: {
      primary: "#3b82f6",
      secondary: "#60a5fa",
      background: "#0c1222",
      foreground: "#dbeafe",
      accent: "#2563eb",
      muted: "#1e293b",
      border: "#334155",
      card: "#1e293b",
      cardForeground: "#dbeafe",
      popover: "#1e293b",
      popoverForeground: "#dbeafe",
      destructive: "#ef4444",
      destructiveForeground: "#fef2f2",
      success: "#10b981",
      warning: "#f59e0b",
      info: "#3b82f6",
    },
    gradients: {
      hero: "linear-gradient(135deg, #1e3a8a 0%, #3b82f6 100%)",
      card: "linear-gradient(135deg, #1e293b 0%, #334155 100%)",
      button: "linear-gradient(135deg, #2563eb 0%, #3b82f6 100%)",
      background: "linear-gradient(180deg, #0c1222 0%, #1e293b 100%)",
    },
    particles: {
      enabled: true,
      density: 100,
      color: "#60a5fa",
      speed: 0.5,
      size: 1,
      opacity: 0.8,
      shape: "circle",
    },
    soundscape: {
      enabled: true,
      url: "/sounds/space-ambient.mp3",
      volume: 0.3,
      loop: true,
      fadeIn: 3000,
      fadeOut: 3000,
    },
    animations: {
      enabled: true,
      intensity: "medium",
      duration: 350,
      easing: "ease-in-out",
    },
  },

  // 7. Tokyo Night
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    description: "City pop with neon aesthetics",
    isSystem: true,
    isPremium: true,
    colors: {
      primary: "#bb9af7",
      secondary: "#9d7cd8",
      background: "#1a1b26",
      foreground: "#c0caf5",
      accent: "#7aa2f7",
      muted: "#24283b",
      border: "#414868",
      card: "#24283b",
      cardForeground: "#c0caf5",
      popover: "#24283b",
      popoverForeground: "#c0caf5",
      destructive: "#f7768e",
      destructiveForeground: "#1a1b26",
      success: "#9ece6a",
      warning: "#e0af68",
      info: "#7aa2f7",
    },
    gradients: {
      hero: "linear-gradient(135deg, #bb9af7 0%, #7aa2f7 100%)",
      card: "linear-gradient(135deg, #24283b 0%, #414868 100%)",
      button: "linear-gradient(135deg, #9d7cd8 0%, #bb9af7 100%)",
      background: "linear-gradient(180deg, #1a1b26 0%, #24283b 100%)",
    },
    particles: {
      enabled: true,
      density: 60,
      color: "#bb9af7",
      speed: 1.5,
      size: 2,
      opacity: 0.6,
      shape: "circle",
    },
    soundscape: {
      enabled: true,
      url: "/sounds/city-pop.mp3",
      volume: 0.4,
      loop: true,
      fadeIn: 2000,
      fadeOut: 2000,
    },
    animations: {
      enabled: true,
      intensity: "high",
      duration: 250,
      easing: "ease-in-out",
    },
  },

  // 8. Nordic Minimal
  {
    id: "nordic-minimal",
    name: "Nordic Minimal",
    description: "Clean, focused simplicity",
    isSystem: true,
    isPremium: false,
    colors: {
      primary: "#5e81ac",
      secondary: "#81a1c1",
      background: "#eceff4",
      foreground: "#2e3440",
      accent: "#88c0d0",
      muted: "#e5e9f0",
      border: "#d8dee9",
      card: "#ffffff",
      cardForeground: "#2e3440",
      popover: "#ffffff",
      popoverForeground: "#2e3440",
      destructive: "#bf616a",
      destructiveForeground: "#eceff4",
      success: "#a3be8c",
      warning: "#ebcb8b",
      info: "#5e81ac",
    },
    gradients: {
      hero: "linear-gradient(135deg, #5e81ac 0%, #88c0d0 100%)",
      card: "linear-gradient(135deg, #ffffff 0%, #eceff4 100%)",
      button: "linear-gradient(135deg, #5e81ac 0%, #81a1c1 100%)",
      background: "linear-gradient(180deg, #eceff4 0%, #e5e9f0 100%)",
    },
    particles: {
      enabled: false,
      density: 0,
      color: "#5e81ac",
      speed: 0,
      size: 0,
      opacity: 0,
      shape: "circle",
    },
    soundscape: {
      enabled: false,
      volume: 0,
      loop: false,
      fadeIn: 0,
      fadeOut: 0,
    },
    animations: {
      enabled: true,
      intensity: "low",
      duration: 300,
      easing: "ease",
    },
  },

  // 9. Corporate Professional
  {
    id: "corporate-professional",
    name: "Corporate Professional",
    description: "Clean, business-focused design",
    isSystem: true,
    isPremium: false,
    colors: {
      primary: "#1e40af",
      secondary: "#3b82f6",
      background: "#ffffff",
      foreground: "#1e293b",
      accent: "#0ea5e9",
      muted: "#f1f5f9",
      border: "#e2e8f0",
      card: "#f8fafc",
      cardForeground: "#1e293b",
      popover: "#ffffff",
      popoverForeground: "#1e293b",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      success: "#16a34a",
      warning: "#ea580c",
      info: "#0284c7",
    },
    gradients: {
      hero: "linear-gradient(135deg, #1e40af 0%, #3b82f6 100%)",
      card: "linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%)",
      button: "linear-gradient(135deg, #1e40af 0%, #3b82f6 100%)",
      background: "linear-gradient(180deg, #ffffff 0%, #f8fafc 100%)",
    },
    particles: {
      enabled: false,
      density: 0,
      color: "#3b82f6",
      speed: 0,
      size: 0,
      opacity: 0,
      shape: "circle",
    },
    soundscape: {
      enabled: false,
      volume: 0,
      loop: false,
      fadeIn: 0,
      fadeOut: 0,
    },
    animations: {
      enabled: true,
      intensity: "low",
      duration: 250,
      easing: "ease-out",
    },
  },

  // 10. Deep Focus
  {
    id: "deep-focus",
    name: "Deep Focus",
    description: "Minimal distractions for concentration",
    isSystem: true,
    isPremium: false,
    colors: {
      primary: "#64748b",
      secondary: "#94a3b8",
      background: "#0f172a",
      foreground: "#f1f5f9",
      accent: "#475569",
      muted: "#1e293b",
      border: "#334155",
      card: "#1e293b",
      cardForeground: "#f1f5f9",
      popover: "#1e293b",
      popoverForeground: "#f1f5f9",
      destructive: "#ef4444",
      destructiveForeground: "#fef2f2",
      success: "#22c55e",
      warning: "#f59e0b",
      info: "#3b82f6",
    },
    gradients: {
      hero: "linear-gradient(135deg, #475569 0%, #64748b 100%)",
      card: "linear-gradient(135deg, #1e293b 0%, #334155 100%)",
      button: "linear-gradient(135deg, #475569 0%, #64748b 100%)",
      background: "linear-gradient(180deg, #0f172a 0%, #1e293b 100%)",
    },
    particles: {
      enabled: false,
      density: 0,
      color: "#64748b",
      speed: 0,
      size: 0,
      opacity: 0,
      shape: "circle",
    },
    soundscape: {
      enabled: true,
      url: "/sounds/white-noise.mp3",
      volume: 0.2,
      loop: true,
      fadeIn: 5000,
      fadeOut: 5000,
    },
    animations: {
      enabled: false,
      intensity: "low",
      duration: 0,
      easing: "linear",
    },
  },

  // 11. Creative Studio
  {
    id: "creative-studio",
    name: "Creative Studio",
    description: "Vibrant, inspiring colors",
    isSystem: true,
    isPremium: true,
    colors: {
      primary: "#ec4899",
      secondary: "#f472b6",
      background: "#fdf2f8",
      foreground: "#831843",
      accent: "#db2777",
      muted: "#fce7f3",
      border: "#fbcfe8",
      card: "#fef3f9",
      cardForeground: "#831843",
      popover: "#fef3f9",
      popoverForeground: "#831843",
      destructive: "#dc2626",
      destructiveForeground: "#fef2f2",
      success: "#10b981",
      warning: "#f59e0b",
      info: "#3b82f6",
    },
    gradients: {
      hero: "linear-gradient(135deg, #ec4899 0%, #f472b6 100%)",
      card: "linear-gradient(135deg, #fef3f9 0%, #fce7f3 100%)",
      button: "linear-gradient(135deg, #db2777 0%, #ec4899 100%)",
      background: "linear-gradient(180deg, #fdf2f8 0%, #fce7f3 100%)",
    },
    particles: {
      enabled: true,
      density: 40,
      color: "#f472b6",
      speed: 1,
      size: 4,
      opacity: 0.4,
      shape: "circle",
    },
    soundscape: {
      enabled: true,
      url: "/sounds/upbeat-ambient.mp3",
      volume: 0.3,
      loop: true,
      fadeIn: 2000,
      fadeOut: 2000,
    },
    animations: {
      enabled: true,
      intensity: "high",
      duration: 300,
      easing: "ease-in-out",
    },
  },

  // 12. Night Owl
  {
    id: "night-owl",
    name: "Night Owl",
    description: "Eye-friendly dark mode",
    isSystem: true,
    isPremium: false,
    colors: {
      primary: "#82aaff",
      secondary: "#c792ea",
      background: "#011627",
      foreground: "#d6deeb",
      accent: "#7fdbca",
      muted: "#01111d",
      border: "#1d3b53",
      card: "#011627",
      cardForeground: "#d6deeb",
      popover: "#011627",
      popoverForeground: "#d6deeb",
      destructive: "#ef5350",
      destructiveForeground: "#ffffff",
      success: "#addb67",
      warning: "#ffcb8b",
      info: "#82aaff",
    },
    gradients: {
      hero: "linear-gradient(135deg, #82aaff 0%, #c792ea 100%)",
      card: "linear-gradient(135deg, #011627 0%, #01111d 100%)",
      button: "linear-gradient(135deg, #7fdbca 0%, #82aaff 100%)",
      background: "linear-gradient(180deg, #011627 0%, #01111d 100%)",
    },
    particles: {
      enabled: true,
      density: 30,
      color: "#82aaff",
      speed: 0.5,
      size: 2,
      opacity: 0.4,
      shape: "circle",
    },
    soundscape: {
      enabled: true,
      url: "/sounds/night-ambient.mp3",
      volume: 0.2,
      loop: true,
      fadeIn: 3000,
      fadeOut: 3000,
    },
    animations: {
      enabled: true,
      intensity: "low",
      duration: 350,
      easing: "ease",
    },
  },
];

export function getThemeById(id: string): ThemeConfig | undefined {
  return SYSTEM_THEMES.find((theme) => theme.id === id);
}

export function getSystemThemes(): ThemeConfig[] {
  return SYSTEM_THEMES.filter((theme) => theme.isSystem);
}

export function getPremiumThemes(): ThemeConfig[] {
  return SYSTEM_THEMES.filter((theme) => theme.isPremium);
}

export function getFreeThemes(): ThemeConfig[] {
  return SYSTEM_THEMES.filter((theme) => !theme.isPremium);
}
